### ISSUE TITLE
Read response from FTP server

### ISSUE THREAD

**Issue by cneira** [miner/clj-ftp#17]
Hi, is it possible to have access to the response of the ftp server after a command is executed? I mean not actual response code but the text that is presented to the user when the commands are typed manually.

Bests

**Comment by miner** [comment]
cli-ftp doesn't expose that as a feature, but you should be able to get the text with (.getReplyString client)

See 
https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPClient.html

**Comment by cneira** [comment]
Thank you very much !
