### ISSUE TITLE
with-ftp silently fails on unsuccessful login

### ISSUE THREAD

**Issue by escherize** [miner/clj-ftp#23]
I am using `with-ftp` to check that a user can successfully login to an FTP or FTPS server. I noticed at line 94 in ftp.clj (https://github.com/miner/clj-ftp/blob/master/src/miner/ftp.clj#L94) the boolean value that `(.login client)` returns is thrown away, but ideally we would keep that information, and perhaps throw an Exception when there's an unsuccessful login. This way we can use the `client-*` functions with the knowledge that we have successfully logged in.

If that sounds reasonable I will submit a PR for it.

**Comment by miner** [comment]
Yes, it sounds like a good idea to check the result of login.  It would be nice to have a test for that, too.

**Comment by escherize** [comment]
Thanks, I have submitted #24 for review.

**Comment by miner** [comment]
PR #26 addressed this
