### ISSUE TITLE
Watch out for passwords with `#` char

### ISSUE THREAD

**Issue by frankitox** [miner/clj-ftp#40]
If your URL has a `#` in the password you'll get an error

```
(.getHost (miner.ftp/as-uri "ftp://user:#@server.com"))
;; => "user"
```

**Comment by miner** [comment]
Good point.  I will have to think about the requirements for URL encoding for special characters.

**Comment by frankitox** [comment]
I've only created the issue in case someone else browses for the problem (I just changed the password in the FTP server).

Thanks for the awesome library!

**Comment by lowecg** [comment]
I just walked into this one.

@frankitox, thanks for raising the ticket!

I appreciate that the URL encoding for connection params embedded in the URL needs a think.

It would also be good not to rely solely on the URL for supplying the credentials. Could we also specify username and password using the `ftp/with-ftp` `params`? E.g.

```clojure
(ftp/with-ftp [client "ftp://ftp.example.com/pub"
               :username "anonymous"
               :password "pwd"]
	(ftp/client-get client "interesting.txt" "stuff.txt"))
```

**Comment by miner** [comment]
The new options for :username and :password are added in release 1.1.0, now available on Clojars.  However, that feature has not been documented in the README yet.

The original issue asked about using a URL such as "ftp://user:#@server.com".  That will still cause an error as the URL must use percent encoding for a handful of characters that are considered special (including space and #).  The correct URL in that case would be: "ftp://user:%23@server.com".  That's a bit tricky so I agree the new keyword options would be simpler to use as the percent encoding will be done internally.  That is, you can use :password "#".  I should note that if you're using :username and :password, you should not also include those values in the URL.

**Comment by lowecg** [comment]
Great stuff, Steve! Thank you
